extends "res://test/test_crouch_v2.gd"
## Supersedes the previous full-clip moving handoff assertions.

func direct_case(stick: Vector2,shift: bool) -> void:
	for frame in 85: await crouch_tick(false)
	for frame in 40: await crouch_tick(false,stick,shift)
	var before: float=body.animation_state.horizontal_speed
	await crouch_tick(true,stick,shift)
	var expected: StringName=(&"CrouchLockedRun" if shift else &"CrouchLocked") if lock.is_locked() else (&"CrouchRun" if shift else &"CrouchWalk")
	check(animation.current_state==expected and animation._playback.get_current_node()==expected,"direct moving entry")
	check(crouch.moving_transition and crouch.collision.shape.height>1.1,"animation independent of smooth capsule shrink")
	check(body.animation_state.horizontal_speed>0 and before>0,"no entry stop")
	check(body._run_time==0 and body.animation_state.gait==0,"standing sprint buildup cleared")
	for frame in 25:
		await crouch_tick(true,stick,shift)
		check(animation.current_state==expected,"no posture or Idle bridge")
	check(absf(body.animation_state.horizontal_speed-(body.run_start_speed if shift else body.walk_speed))<.03,"crouch speed preserved")
	await crouch_tick(false,stick,shift)
	check(animation.current_state==&"Locomotion" and animation._playback.get_current_node()==&"Locomotion","direct moving exit")
	check(crouch.collision.shape.height<1.8,"safe smooth expansion")
	check(tree.get("parameters/Locomotion/playback").get_current_node()==(&"Locked" if lock.is_locked() else &"Loops"),"direct current standing mode")
	check(animation.gait_blend>=1.0,"standing destination has no idle weight")
	for frame in 25: await crouch_tick(false,stick,shift)
	check(not crouch.active(),"capsule finishes without a posture animation")
	check(absf(crouch.collision.position.y-crouch.collision.shape.height*.5-crouch.base_y)<.001,"capsule base preserved")

func run() -> void:
	lab=load("res://test/player_v2_lab.tscn").instantiate()
	root.add_child(lab)
	body=lab.get_node("PlayerV2")
	animation=body.get_node("AnimationController")
	tree=body.get_node("AnimationTree")
	lock=body.get_node("LockOnController")
	dummy=lab.get_node("LockOnTargetDummy")
	cam=body.get_node("CameraRig")
	dodge=body.dodge
	assist=body.roll_traversal
	crouch=body.crouch
	body.set_physics_process(false)
	animation.set_physics_process(false)
	cam.set_process(false)
	tree.callback_mode_process=AnimationMixer.ANIMATION_CALLBACK_MODE_PROCESS_MANUAL
	box(Vector3(200,-.25,0),Vector3(400,.5,400))
	await reset_at(Vector3(200,.1,10))
	for shift in [false,true]: await direct_case(Vector2(0,-1),shift)
	for frame in 85: await crouch_tick(false)
	for frame in 500: await crouch_tick(false,Vector2(0,-1),true)
	check(body.animation_state.gait==2,"sprint setup")
	await crouch_tick(true,Vector2(0,-1),true)
	check(animation.current_state==&"CrouchRun" and body._run_time==0,"sprint directly becomes supported crouch run")
	await reset_at(Vector3(200,.1,10))
	for frame in 85: await crouch_tick(false)
	await crouch_tick(true)
	check(animation.current_state==&"CrouchEnter","stationary entry uses CRC clip")
	for frame in 14: await crouch_tick(true)
	await crouch_tick(true,Vector2(0,-1))
	check(animation.current_state==&"CrouchWalk","movement interrupts stationary entry once capsule ready")
	for frame in 25: await crouch_tick(true)
	await crouch_tick(false)
	check(animation.current_state==&"CrouchExit","stationary exit uses CRC clip")
	await crouch_tick(false,Vector2(0,-1))
	check(animation.current_state==&"Locomotion","movement interrupts stationary exit")
	for frame in 85: await crouch_tick(false)
	await reset_at(Vector3(200,.1,10))
	for frame in 85: await crouch_tick(true)
	var roof:=box(Vector3(200,1.45,10),Vector3(8,.3,8))
	for frame in 15: await crouch_tick(false,Vector2(0,-1))
	check(crouch.active() and not crouch.can_stand and animation.current_state==&"CrouchWalk","blocked exit keeps moving crouch")
	roof.queue_free()
	for frame in 4: await crouch_tick(false,Vector2(0,-1))
	check(animation.current_state==&"Locomotion","clearance enables direct moving exit")
	for frame in 85: await crouch_tick(false)
	await reset_at(Vector3(200,.1,10))
	dummy.position=Vector3(200,0,2)
	lock.toggle()
	for shift in [false,true]:
		for stick in [Vector2(0,-1),Vector2(-1,0),Vector2(1,0),Vector2(0,1)]:
			await direct_case(stick,shift)
	print("CROUCH_MODIFIER_V2: ","PASS" if failures.is_empty() else failures)
	quit(0 if failures.is_empty() else 1)
